# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWindowNoSpotifyTest.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindowNoSpotify(object):
    def setupUi(self, MainWindowNoSpotify):
        MainWindowNoSpotify.setObjectName("MainWindowNoSpotify")
        MainWindowNoSpotify.resize(800, 600)

        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("Resources/Images/MusicPyLogo.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)

        MainWindowNoSpotify.setWindowIcon(icon)
        MainWindowNoSpotify.setStyleSheet("")

        self.centralwidget = QtWidgets.QWidget(MainWindowNoSpotify)
        self.centralwidget.setObjectName("centralwidget")

        self.pushButtonGenerate = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonGenerate.setGeometry(QtCore.QRect(70, 360, 311, 151))
        font = QtGui.QFont()
        font.setFamily("Tibetan Machine Uni")
        font.setPointSize(18)
        self.pushButtonGenerate.setFont(font)
        self.pushButtonGenerate.setStyleSheet("border-color: rgb(0, 0, 0);\n"
"border-style: solid;\n"
"border-width: 3px;\n"
"\n"
"background-color: rgb(108, 108, 108);\n"
"")
        self.pushButtonGenerate.setObjectName("pushButtonGenerate")
        self.pushButtonGenerate.clicked.connect(lambda: self.generateTrack())


        self.labelSongInfoBackground = QtWidgets.QLabel(self.centralwidget)
        self.labelSongInfoBackground.setGeometry(QtCore.QRect(60, 50, 681, 271))
        font = QtGui.QFont()
        font.setFamily("Tibetan Machine Uni")
        font.setPointSize(48)
        font.setBold(True)
        font.setWeight(75)
        self.labelSongInfoBackground.setFont(font)
        self.labelSongInfoBackground.setStyleSheet("background-color: rgb(108, 108, 108);\n"
"\n"
"border-color: rgb(0, 0, 0);\n"
"border-width: 3px;\n"
"border-style: solid;\n"
"\n"
"font-weight: bold;")
        self.labelSongInfoBackground.setText("")
        self.labelSongInfoBackground.setObjectName("labelSongInfoBackground")

        self.labelBackground = QtWidgets.QLabel(self.centralwidget)
        self.labelBackground.setGeometry(QtCore.QRect(-10, 0, 815, 600))
        self.labelBackground.setStyleSheet("")
        self.labelBackground.setText("")
        self.labelBackground.setPixmap(QtGui.QPixmap("Resources/Images/backgroundImage.png"))
        self.labelBackground.setObjectName("labelBackground")

        self.labelGeneratedSongName = QtWidgets.QLabel(self.centralwidget)
        self.labelGeneratedSongName.setGeometry(QtCore.QRect(80, 60, 311, 131))
        font = QtGui.QFont()
        font.setFamily("Tibetan Machine Uni")
        font.setPointSize(28)
        self.labelGeneratedSongName.setFont(font)
        self.labelGeneratedSongName.setObjectName("labelGeneratedSongName")

        self.labelGeneratedSongArtist = QtWidgets.QLabel(self.centralwidget)
        self.labelGeneratedSongArtist.setGeometry(QtCore.QRect(66, 190, 331, 131))
        font = QtGui.QFont()
        font.setFamily("Tibetan Machine Uni")
        font.setPointSize(28)
        self.labelGeneratedSongArtist.setFont(font)
        self.labelGeneratedSongArtist.setObjectName("labelGeneratedSongArtist")

        self.labelSongNameVariable = QtWidgets.QLabel(self.centralwidget)
        self.labelSongNameVariable.setGeometry(QtCore.QRect(406, 64, 321, 121))
        font = QtGui.QFont()
        font.setFamily("Tibetan Machine Uni")
        font.setPointSize(24)
        self.labelSongNameVariable.setFont(font)
        self.labelSongNameVariable.setText("")
        self.labelSongNameVariable.setObjectName("labelSongNameVariable")

        self.labelSongArtistVariable = QtWidgets.QLabel(self.centralwidget)
        self.labelSongArtistVariable.setGeometry(QtCore.QRect(406, 190, 321, 121))
        font = QtGui.QFont()
        font.setFamily("Tibetan Machine Uni")
        font.setPointSize(24)
        self.labelSongArtistVariable.setFont(font)
        self.labelSongArtistVariable.setText("")
        self.labelSongArtistVariable.setObjectName("labelSongArtistVariable")

        #Invisible song id
        self.labelSongID = QtWidgets.QLabel(self.centralwidget)
        self.labelSongID.setGeometry(QtCore.QRect(10, 556, 31, 20))
        font = QtGui.QFont()
        font.setPointSize(1)
        self.labelSongID.setFont(font)
        self.labelSongID.setText("")
        self.labelSongID.setObjectName("labelSongID")

        self.pushButtonOpenSpotify = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonOpenSpotify.setGeometry(QtCore.QRect(419, 360, 311, 151))
        font = QtGui.QFont()
        font.setFamily("Tibetan Machine Uni")
        font.setPointSize(18)
        self.pushButtonOpenSpotify.setFont(font)
        self.pushButtonOpenSpotify.setStyleSheet("border-color: rgb(0, 0, 0);\n"
"border-style: solid;\n"
"border-width: 3px;\n"
"\n"
"background-color: rgb(108, 108, 108);\n"
"")
        self.pushButtonOpenSpotify.setObjectName("pushButtonOpenSpotify")
        self.pushButtonOpenSpotify.clicked.connect(lambda: self.openSpotify())

        self.labelBackground.raise_()
        self.pushButtonGenerate.raise_()
        self.labelSongInfoBackground.raise_()
        self.labelGeneratedSongName.raise_()
        self.labelGeneratedSongArtist.raise_()
        self.labelSongNameVariable.raise_()
        self.labelSongArtistVariable.raise_()
        self.pushButtonOpenSpotify.raise_()

        MainWindowNoSpotify.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindowNoSpotify)
        self.statusbar.setObjectName("statusbar")

        MainWindowNoSpotify.setStatusBar(self.statusbar)

        self.actionSpotify_Login = QtWidgets.QAction(MainWindowNoSpotify)
        self.actionSpotify_Login.setObjectName("actionSpotify_Login")

        self.retranslateUi(MainWindowNoSpotify)
        QtCore.QMetaObject.connectSlotsByName(MainWindowNoSpotify)

    def retranslateUi(self, MainWindowNoSpotify):
        _translate = QtCore.QCoreApplication.translate
        MainWindowNoSpotify.setWindowTitle(_translate("MainWindowNoSpotify", "MusicPy: Generate"))
        self.pushButtonGenerate.setText(_translate("MainWindowNoSpotify", "Generate Song"))
        self.pushButtonGenerate.setShortcut(_translate("MainWindowNoSpotify", "Ctrl+G"))
        self.labelGeneratedSongName.setText(_translate("MainWindowNoSpotify", "Generated Song: "))
        self.labelGeneratedSongArtist.setText(_translate("MainWindowNoSpotify", "  Song Artist: "))
        self.pushButtonOpenSpotify.setText(_translate("MainWindowNoSpotify", "Open In Spotify"))
        self.pushButtonOpenSpotify.setShortcut(_translate("MainWindowNoSpotify", "Ctrl+O"))
        self.actionSpotify_Login.setText(_translate("MainWindowNoSpotify", "Spotify Login"))

    #Function for the generate random song button
    def generateTrack(self):
        from getMusic import Music
        try:
            randSong = Music()
            self.randSongName, self.randArtistName, self.randSongID = randSong.getRandomAlbum()
        except:
            try:
                randSong = Music()
                self.randSongName, self.randArtistName, self.randSongID = randSong.getRandomAlbum()
            except:
                try:
                    randSong = Music()
                    self.randSongName, self.randArtistName, self.randSongID = randSong.getRandomAlbum()
                except:
                    randSong = Music()
                    self.randSongName, self.randArtistName, self.randSongID = randSong.getRandomAlbum()

        self.labelSongNameVariable.setText(self.randSongName)
        self.labelSongArtistVariable.setText(self.randArtistName)
        self.labelSongNameVariable.adjustSize()
        self.labelSongArtistVariable.adjustSize()
        songIDText = open("Resources/SongID.txt", "w")
        songIDText.write(self.randSongID)
        songIDText.close()

    #Function that opens spotify using the extracted link
    def openSpotify(self):
        import webbrowser
        songIDText = open("Resources/SongID.txt", "r")
        self.songID = songIDText.read()
        webbrowser.open(self.songID, new=2)
        songIDText.close()


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindowNoSpotify = QtWidgets.QMainWindow()
    ui = Ui_MainWindowNoSpotify()
    ui.setupUi(MainWindowNoSpotify)
    MainWindowNoSpotify.show()
    sys.exit(app.exec_())
